// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaK8S-BFxu6LbG7IkMaM6b64PS4ttcjwQ',
    appId: '1:123227311444:android:5453c7545c3794b55d0cc1',
    messagingSenderId: '123227311444',
    projectId: 'chattingapp-bbb4f',
    storageBucket: 'chattingapp-bbb4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPymmkhkG4AP6oWbi-Xc4Zo-6euTzWkmo',
    appId: '1:123227311444:ios:f9ba8002cdefce4b5d0cc1',
    messagingSenderId: '123227311444',
    projectId: 'chattingapp-bbb4f',
    storageBucket: 'chattingapp-bbb4f.appspot.com',
    androidClientId: '123227311444-jske1gqhe75l9ns6985hu9c87nu8ji42.apps.googleusercontent.com',
    iosClientId: '123227311444-d0ahf116t5m7kr2c0g3ucbf369kbvkdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
